#! /bin/sh

sxhkd &
sh ~/.config/polybar/launch.sh &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V
bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Chromium desktop='^4'
bspc rule -a TelegramDesktop desktop='^5'
