#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^1'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a discord desktop='^9'
bspc rule -a TelegramDesktop desktop='^10'

# touchpad
xinput set-prop "ELAN0710:01 04F3:30ED Touchpad" "libinput Tapping Enabled" 1

# autostart applications
dex -a

mpc random && mpc load myplaylist

feh --bg-fill --randomize ~/.config/wallpaper

